### ISSUE TITLE
Ei näyttäisi settings.mode == 2 toimivan?

### ISSUE THREAD

**Issue by jrajahalme** [jisotalo/shelly-porssisahko#1]
Tämä `settings.mode == 2` vaihtoehto ei näyttäisi toimivan näistä syistä:
- Time Zonesta puuttuu tuntien ja minuuttien välistä kaksoispiste (https://docs.oracle.com/javase/8/docs/api/java/time/ZonedDateTime.html)
  - `+` merkki pitää olle URL enkoodattu muotoon `%2b`
  - esimerkki toimivasta URLista: https://dashboard.elering.ee/api/nps/price?start=2023-08-28T00:00:00%2b03:00&end=2023-08-29T00:00:00%2b03:00

**Comment by jrajahalme** [comment]
Poistin kuvauksesta viittaukset puuttuvaan fi-alueen hintatietoon, olivathan ne siellä.

**Comment by jisotalo** [comment]
Moro!

Testasin nyt ja minulla toimii kyllä hienosti. Nykyisellään skriptihän käyttää UTC+0 -aikaa koska en saanut aikavyöhykkeitä toimimaan. Eli juuri äsken kun käynnistin, hintatiedot haettiin osoitteesta

https://dashboard.elering.ee/api/nps/price?start=2023-09-02T00:00:00Z&end=2023-09-02T23:59:00Z

Mutta tuo sinun formaatti aikavyöhykkeelle näyttää toimivan, joten ilman muuta laitetaan skriptiin uusi asetus ja käytetään suoraan oikeaa aikavyöhykettä. Koitin itse eri formaatteja mutta en löytänyt oikeaa. Näin saadaan toimintakin järkevämmäksi, eli käytetään suomen vuorokautta eikä UTC+0 -vuorokautta.

![image](https://github.com/jisotalo/shelly-porssisahko/assets/13457157/2dde7774-c496-4abb-b3e8-6dcca77d8a2c)

**Comment by jisotalo** [comment]
Versio 2.0.0 julkaistu
