### ISSUE TITLE
Maakoodi

### ISSUE THREAD

**Issue by luotope** [jisotalo/shelly-porssisahko#10]
Koodi toimii hienosti ja käyttöliittymä on hyvä (Shelly Plus plug s). Olisi hienoa jos voisi valita maakoodin, niin että tätä voisi käyttää myös toisella aikavyöhykkeellä, esim ruotsissa (siis suomeksi). Olisiko tulossa tällainen modaus? Toivottavasti, koska olisi ihan kymppi sovellus muuten.

**Comment by jisotalo** [comment]
Moi! Hyvä että pelittää, en itse ole vielä kokeillut tuolla plugilla.

Eikös tuo pitäisi toimia OK uusimmalla versiolla kun asetat Shellyn asetuksista eri aikavyöhykkeen, oletko kokeillut?

**Comment by luotope** [comment]
Moi. Juu tuo tuli mieleeni myös kysymykseni kirjoittamisen jälkeen. En vielä kokeillut, mutta selvitän.
Toinen juttu on kyllä, että tuo elering.ee ei näytä toimittavan ruotsin hintoja, eli pitäisi löytää vastaava csv-palvelu jossa nuo ruotsin eri alueet olisi mukana. Tai ehkä trvittaessa sitten tuottaa omalle palvelimelle nordpoolin json filestä vastaava csv tiedosto omaan käyttöön.

Kiitti
Petri
________________________________
Lähettäjä: Jussi Isotalo ***@***.***>
Lähetetty: torstai 9. marraskuuta 2023 8.50
Vastaanottaja: jisotalo/shelly-porssisahko ***@***.***>
Kopio: luotope ***@***.***>; Author ***@***.***>
Aihe: Re: [jisotalo/shelly-porssisahko] Maakoodi (Issue #10)


Moi! Hyvä että pelittää, en itse ole vielä kokeillut tuolla plugilla.

Eikös tuo pitäisi toimia OK uusimmalla versiolla kun asetat Shellyn asetuksista eri aikavyöhykkeen, oletko kokeillut?

**Comment by jisotalo** [comment]
Joo se on kyllä totta, Ruotsin hintoja ei tuolta saa.
