### ISSUE TITLE
Lämpötilaohjaus mukaan?

### ISSUE THREAD

**Issue by ROGRFI** [jisotalo/shelly-porssisahko#12]
Olen laittanut tällaisen shelly PM1+ korvaamaan lattalämmityksen termostaattia. Olisiko tähän ohjelmaan mahdollista laittaa lämpötilaohjaus? Nyt kun olen asettanut shellyn omasta termarista lämpötilaohjauksen, niin tämä scripti ohjaa shellyä on/off ja shelly ei välitä mitään tuosta lämpötilasta vaan paahtaa päällä miten tuo pörssiohjaus menee. Aluksi ajattelin hoitaa noiden ohjausta HA käsin, mutta kyllä tällainen stand alone webbiservu on parempi ratkaisu

**Comment by jisotalo** [comment]
Kyllä se on teknisesti mahdollista. Suunnitelmissa on lisätä ominaisuus, että pystyisi helposti lisäämään omaa koodia rinnalle, mutta en ole vielä ehtinyt.

Ajatus olisi että kun tämä skripti on päätöksensä tehnyt, kutsutaan vielä erillistä funktiota, jonka voi itse lisätä halutessaan. Tässä funktiossa voi sitten tehdä lämpötilatarkasteluita ym. ja tarvittaessa muuttaa ohjausta päälle tai pois.

En usko että rupeen suoraan tähän rakentamaan tuollaista mutta ei sitä koskaan tiedä. Nyt kun shelly muutti firmistään, on muille skripteille hyvin tilaa, eli kaikki on mahdollista.

**Comment by jisotalo** [comment]
Moro @ROGRFI 

Tässä kävikin niin että nyt tuli julkaistua versio 2.8.0, mikä tukee myös tätä.

Yksinkertainen esimerkki, jonka voi myös asentaa shellyn library-napin kautta:
https://github.com/jisotalo/shelly-porssisahko#l%C3%A4mp%C3%B6tilaohjaus-shelly-plus-add-on-ja-ds18b20

Tätä funktiotahan voi jalostaa miten vaan ja vaikka hakea tiedot jostain muualta HTTP:llä.

**Comment by ROGRFI** [comment]
Huomasin meilistä, että olit vastaillut tähän. Kiitoksia kun viitsit päivitellä tätä! 

Kokeilin tuota uutta lämpötilaohjausta, niin nyt tuo muuttaa tuon pörssiohjauksen normaaliksi termariksi. Ohjaus välittää nyt pelkästään lämpötilasta ja sähkön hinnalla ei ole väliä. Itse hain tällaista ohjausta: 

Tuossa alkuperäisessä pörssisähköohjauksessa määritetään ehdot, milloin sähköä on tarjolla. Tuo lämpötilaohjaus toimisi sen mukaan, miten sähköä on saatavilla. Kun sähköä on saatavilla, niin se laittaa lämmityksen päälle, mikäli sille on tarvetta.

Käytän tätä erillisen autotallin lämmittämiseen, jossa koitan pitää lämpötilan hieman plussan puolella. Voisihan tuossa olla joku lämpötila-arvo esim. +1C, jolloin lämmitys lähtee päälle sähkön hinnasta huolimatta ja lämmitys olisi päällä, kunnes lämpötila on noussut +3C

Koitin katsoa tuota koodia, miten sen saisi kirjoitettua siihen. Tuossa ensimmäisessä rivissä on kait tuo pääohjelma koodi yhdellä rivillä? Siitä oli hieman vaikea lähteä tutkimaan miten tuon koodin olisi muuttanut tuollaiseksi, kuin kuvailin.

**Comment by jisotalo** [comment]
Eikös tuo esimerkki toimi lähestulkoon noin. Eli 
- annetaan pörssisähkön ohjata vapaasti, mikäli lämpötila on +5..+15 välillä.
- jos lämpötila nousee yli +15 todetaan ettei ole tarvetta, vaikka olisi halpaa -> tiputetaan pois.
- jos lämpötila on alle +5, laitetaan ohjaus päälle vaikka ei olisi halpaa, kunnes se on yli +5.

Eli nyt vaan muuttaa 15 halutuksi ylärajaksi, mitä lämpimämmäksi ei haluta ohjata. Ja jos ei halua että on alarajaa, muuttaa vaikka 5 --> -99. Näin mennään pörssisähkön mukaan paitsi jos on liian lämmintä.

**Comment by jisotalo** [comment]
@ROGRFI saitko tähän selvyyttä?

**Comment by jisotalo** [comment]
Versiossa 2.10.2 tullut lisää uudistuksia. Nyt lämpötila näytetään myös käyttöliittymässä.

Suljen tämän issuen toistaiseksi.
