### ISSUE TITLE
Laitteen nimen näyttäminen tila-sivulla

### ISSUE THREAD

**Issue by salakkju** [jisotalo/shelly-porssisahko#13]
Moro, asentelin skriptin parille laitteelle ja ensisilmäykseltä skripti tuntuisi toimivan kivasti. 

Itselle olisi avuksi jos tila-sivulla näkyisi laitteen nimi jonka tilaa ollaan tarkastelemassa. Eli varmaankin API rajapinnasta GET:<LAITTEEN-IP>/shelly paluutiedoissa tuleva name-elementti voisi olla toimiva tähän ainakin.

**Comment by jisotalo** [comment]
Moro, kiva kuulla että toimii.

Tarkoitatko tuota nimeä minkä voi laittaa asetuksissa? Ja näkyy esim http://IP/rpc/Sys.GetConfig datassa?
![image](https://github.com/jisotalo/shelly-porssisahko/assets/13457157/2cbaa3de-3588-4220-aee0-2269cf28ac8f)

Voisi olla hyvä lisäys, pistän työlistalle

**Comment by jisotalo** [comment]
2.8.0 julkaistu ja nyt nimi näkyy:
![image](https://github.com/jisotalo/shelly-porssisahko/assets/13457157/e3aef662-177a-412d-b378-36ca4e9bb2a5)

**Comment by tkkoivula** [comment]
Päivitin just versioon 2.8.1. Tuo sama laitteen nimi voisi näkyä myös web-sivun "title"nä. Nythän siellä näkyy vain "Pörssisähkö".
(<title>Pörssisähkö</title>)

**Comment by jisotalo** [comment]
@tkkoivula hyvä idea. Teinpä tuon saunaa odotellessa eli löytyy nyt uudesta 2.8.2:sta.
