### ISSUE TITLE
Useampikanavainen rele - oma ohjaus eri kanaville (Pro4PM)

### ISSUE THREAD

**Issue by tkkoivula** [jisotalo/shelly-porssisahko#16]
Moi,

Täällä tämä nyt ollut ajossa Pro4PM:ssa jokusen viikon, ihan loistavaa :) Paitsi että ei taida saada ohjattua kuin yhtä relettä? Pro4PM:ssä siis 4 kanavaa. Onnistuisko miten helposti lisätä samaan skriptiin useamman releen ohjaukset? Nykyisellään ohjaan yhtä relettä tällä skriptillä ja muita kanavia joko shellyn omalla ajastimella tai HA:lla.

**Comment by jisotalo** [comment]
Moro ja kiitoksia!

Tästä olikin keskustelua facebookissa jossain kohti:
https://www.facebook.com/groups/shellytuki/posts/3686797774886830/?comment_id=3687768558123085&reply_comment_id=3690163787883562

Olisi kyllä hyvä idea, mutta vaatii järjestelmän ja asetusten uudelleensuunnittelun. En usko että vielä hetkeen semmoista joudan tekemään. Itse kun olen käyttänyt vain yhden lähdön laitteita, en osannut lähteä tämmöistä heti alusta lähtien miettimään.

Laitetaan siis listalle ja katsotaan! :)

**Comment by tkkoivula** [comment]
Arvelinkin ettei se ihan copy/paste -tyyliin mene. :) Mutta hyvä näinkin, tämä web-käyttöliittymä on paljon parempi kuin esim. spot-hinta.fi -skriptiin tehtävät asetukset. Lisäksi tästä näkee selvästi mitä tapahtuu vuorokauden aikana.

**Comment by tkkoivula** [comment]
Skriptin pystyy näemmä asentamaan kahteen kertaan eri nimillä.
 http://192.168.14.174/script/1#tab-config
 http://192.168.14.174/script/3#tab-config
Sotkeekohan noiden conffit toisiaan? Pitääpä tutkia. :)

**Comment by jisotalo** [comment]
Itsekin tykkään tuosta että näkee selkeästi mitä tapahtuu, eikä ole riippuvainen muiden palveluista. Siksi tämä tulikin tehtyä.

Valitettavasti konffit sotkee toisiaan vaikka voikin asentaa useaan kertaan. Periaatteessa toiminnee kunnes Shelly käynnistyy uudelleen, sitten molemmilla on taas samat asetukset.

Ratkaisu on se että määrittää toiselle skriptille asetukset koodin puolelta, tällöin asetuksia ei vaan voi tallentaa selaimen kautta (mutta valvonta toimii). Eli jos asennat toisen skriptin library-napilla ja valitsekin sieltä **ESIMERKKI: Pörssisähköohjaus ja asetukset skriptissä**. Sitten käsin kirjoittelet halutut asetukset 
https://github.com/jisotalo/shelly-porssisahko#esimerkki-asetukset-suoraan-skriptiin-ilman-k%C3%A4ytt%C3%B6liittym%C3%A4%C3%A4

**Comment by tkkoivula** [comment]
Kopsasin jo skriptin notepadiin, find/replace porssi-config > porssi-conf2. Nyt on ajossa samassa shellyssä kaksi skriptiä eri asetuksilla. Päivitettävyyden kannalta ei tietty ole paras mahdollinen ratkaisu.
![image](https://github.com/jisotalo/shelly-porssisahko/assets/58558014/ea0bc963-5d71-438d-a228-7d86833dc0a6)
Sitten se idea: "porssi-config" key voisi olla nimeltään "porssi-config-x" jossa x= skriptin numero?

**Comment by tkkoivula** [comment]
> eikä ole riippuvainen muiden palveluista.

Tämä ehdottomasti minullakin se syy miksi haluan hoitaa ainakin tärkeät ohjaukset itse shellyssä enkä homeassistantissa.

**Comment by jisotalo** [comment]
Hyvä että sait toimimaan, noin asetusten täytyisikin olla jotta tukee useaa skriptiä. 

Tuommoinen muutos täytyisi vaan julkaista versiossa 3 tai sitten varmistaa takaisinpäin yhteensopivuus, ettei asetukset katoa päivittäessä.

**Comment by tkkoivula** [comment]
Ei se ihan noin helposti onnistunut, asetuksia ei saanut tallennettua. No asensin nodejs:n ubuntuun, muutin konffi-keyn nimen sorsiin ja käänsin itselleni ikioman version 2.8.2.1. :) 

USER_OVERRIDE voisi ehkä olla hyvä paikka määritellä konffi-keyn nimi. Säilyisi yhteensopivuus taaksepäin ja päivittäminen olisi suhteellisen helppo operaatio.

**Comment by jisotalo** [comment]
Kyllä tuo pitäisi toimia, haluatko laittaa koodin mitä kokeilit?

Periaatteessa voisi kyllä olla ihan asetus käyttöliittymällä, jossa voi määrittää mihin asetukset tallennetaan.

**Comment by jisotalo** [comment]
Uudessä 2.9.0 versiossa voi ohjata useampaa lähtöä samaan aikaan. Tämä ei siis kuitenkaan ratkaise tätä ongelmaa, missä halutaan ohjata lähtöjä eri asetuksilla.

**Comment by tkkoivula** [comment]
Hyvä homma, eteenpäin mennään. :) Ja kun näitä nyt saa itse kääntäen ajoon samaan purkkiin kaksi, se riittää minulle toistaiseksi! :)

**Comment by jisotalo** [comment]
@tkkoivula 

Uutta versiota pukkaa, muistia menee nyt huipussaan noin 15kt. Eli ei välttämättä kaksi skriptiä enää pyöri samaan aikaan.

Kannattaa pysyä siis vanhassa :)

Tuon useamman ohjauksen versio on työn alla mutta siinä on aika paljon tekemistä.

**Comment by tkkoivula** [comment]
> Uutta versiota pukkaa, muistia menee nyt huipussaan noin 15kt. Eli ei välttämättä kaksi skriptiä enää pyöri samaan aikaan.
> Kannattaa pysyä siis vanhassa :)
> Tuon useamman ohjauksen versio on työn alla mutta siinä on aika paljon tekemistä.

Jees. Nuo kaksi 2.8.2 -versiota on toimineet ihan hienosti yhdessä purkissa. :) 

Näkeekö tuon muistinkäytön jostain?

**Comment by jisotalo** [comment]
Muistinkäytön näkee URL-osoitteesta `http://ip-osoite/rpc/Shelly.GetStatus`:
![image](https://github.com/jisotalo/shelly-porssisahko/assets/13457157/c5d960f3-635b-4f9c-8f53-eb47a54a22b6)

Itse asiassa yksi ratkaisu tähän olisi että tekee oman buildin missä historia ja/tai huomisen hintojen haku on pois käytöstä. Tällöin muistia käytetään vähemmän.

**Comment by KSkalliswatti** [comment]
Kahden päivän kokemuksella..... 👍
Mutta mulla 2-kanavainen
Sähkökatkon jälkeen toimii viimeisen talletetun asetuksen mukaan.
Ei tarvitse muuta, kun valita toimimattoman puolen nettisivu ja määritellä ja tallettaa. Ja molemmat toimii.
Näin amatöörinä ajattelen ,että laitetaan parametrejä kanavien määrän verran talteen (jonnekkin mihin mahtuu) ja koodari ajaa kanavien määrän verran parametrejä aina bootin jälkeen.
Jatkakaa...seuraan mielenkiinnolla ja 1-kanavainen  varmaan toimii hienosti.

**Comment by jisotalo** [comment]
@KSkalliswatti  Kiva kuulla että pelittää!

Tosiaan otin työn alle tuon oman version tekemisen, mikä tallentaa asetukset skriptinumerokohtaisesti. Näin pystyisi ajamaan useaa rinnakkain helposti.

Luultavasti ainakin seuraavan päivän hinnat pitää jättää pois, jotta muisti varmasti riittää.

**Comment by KSkalliswatti** [comment]
Odotellaan. Ei mulla kiirettä.
Jätä 1-kanavainen omaksi versioksi. Huominen on hyvä nähdä.
Ja taidan käyttää 1-kanavaisia. Oma ip on selvempi.

**Comment by jisotalo** [comment]
Tämä on yhä ajankohtainen, sillä en ole saanut aikaiseksi tehdä parannusta. Lisään tähän ohjeen, jonka lähetin eräälle aiheesta kysyjälle.

Eli näin saa useamman skriptin pyörimään samaan aikaan omilla asetuksilla:

---

Eli jos haluaa kikkailla, tuon saa toimimaan useilla asetuksilla siten, että laittaa toisen skriptin ja muokkaa siitä kaikki "porssi-config" -> esim "porssi-config2".
![image](https://github.com/user-attachments/assets/166ea283-a9cc-4085-b154-3e55b65bb607)

Tällöin vaan on teoriassa vaarana, että muisti loppuu, jos skriptit tekevät asioita _juuri_ samaan aikaan.

Sen jälkeen molemmat skriptit konfiguroidaan selaimella omilta sivuiltaan, toinen esim http://ip-osoite/script/1 ja toinen http://ip-osoite/script/2 .

**Comment by tkkoivula** [comment]
![image](https://github.com/user-attachments/assets/200fa648-ea2e-4731-b1a8-ec86a9f92c13)

Mulla on tuo itsekäännetty toinen skripti ollut nyt ajossa hyvän aikaa. Versio 2.12.5. Hyvin on toiminut kun ei koske :). Muisti lienee kuitenkin aika lailla vähissä, muutaman kerran olen huomannut että skripti kaatuu kun menee asetuksiin. 

Shellyn firmiksen päivitin hetki sitten tuohon versioon 1.4.2.

**Comment by tkkoivula** [comment]
![image](https://github.com/user-attachments/assets/fd01fdde-7b57-49d1-9b54-8b16e7a8dcad)

**Comment by jisotalo** [comment]
Hyvä kuulla!

Kyllähän tää olis ihan ratkaistavissa. Ei vaan ole itsellä ollut tarvetta, joten ajankäyttö kohdistunut muuhun. Ja ei ole myöskään useampikanavaista relettä.

**Comment by jisotalo** [comment]
@tkkoivula  @KSkalliswatti 
Nyt on työn alla v3, joka tukee kolmea eri ohjausta samalla skriptillä.

Onko kiinnostuneita testaajia? Kohta voisi olla valmis betatestaukseen.
![chrome_mG8ewfB3pE](https://github.com/user-attachments/assets/f00f7c72-36d2-4bd6-aec3-202bd5050237)

**Comment by vettenj** [comment]
Joo mukana testaamassa, olinhan yksi monista jotka tällaista ovat toivoneet.

**Comment by KSkalliswatti** [comment]
Mökkihommelit loppuu ... testiaikaa varmaan löytyy

**Comment by tkkoivula** [comment]
Jees, testaillaan! Nyt en ole shellyjen vieressä pariin viikkoon mutta eiköhän tuota uskalla etänäkin kokeilla.

**Comment by jisotalo** [comment]
Dodii, nyt on ensimmäinen beta ulkona:
https://github.com/jisotalo/shelly-porssisahko/tree/dev-v3

En ole vielä testannut pro-mallilla, mutta muuten kyllä. 

Bugeja ja ongelmia voi löytyä, joten kannattaa varautua. Vanhan version voi aina pistää takaisin. Asetukset nollaantuu, mutta vanhat asetukset jää jemmaan jos palaa vanhaan versioon.

@vettenj @KSkalliswatti @tkkoivula

**Comment by jisotalo** [comment]
Beta 2 julkaistu! Oli jäänyt bugi, jonka takia varmuustuntien ja pakko-ohjauksien asetukset eivät näkyneet. Tallennus kyllä toimi OK. Facebookista tuli raporttia.

## [3.0.0-beta2] - 03.11.2024
**HUOM:** Tämä on julkinen testiversio. Skriptissä voi olla vielä ongelmia ja se voi vaikka kaatua yllättäen.

- Bugikorjaus: Varmuustuntien ja pakko-ohjattujen tuntien asetukset eivät vastanneet todellisia asetuksia

**Comment by KSkalliswatti** [comment]
Mökillä vielä asun ja testirauta talvikodossa. Täällä mulla vain "töpseleitä". Asensin siihen..toimii
Pitäiskö ohjattavat lähdöt perusasento ollaX ei 0
Jos sulla ohjauskanava vaikka#2 ja sulla jää lähtö päivittämättä menee väärälle kanavalle

**Comment by jisotalo** [comment]
@KSkalliswatti 

Hienoa! 

Sinänsä ihan totta, että nyt joku voi laittaa väärälle ohjaukselle. Mutta omasta mielestäni se on käyttäjän vika. Parempi vaan että oletusasetukset ovat sinänsä toimivat ja lähtö 0 löytyy varmasti kaikista laitteista.

**Comment by KSkalliswatti** [comment]
Tämä tietokonehomma on yhtä "täpänhakemista"..... missä täppä ja onko se väärässä asennossa.
Nyt kun tähän hommaan taas syvennyin tuli mieleen
Koska on kulutusmittauksella varustettuja Shellyjä ja siirtohinta ja alvi ja sähkövero tiedetään voidaan laskea hinta ja näyttä se
Ja tässä monikanavaisessa vois olla jossain rivi, joissa näkyis koko ajan mitä mikäkin kanava ajaa

________________________________
Lähettäjä: Jussi Isotalo ***@***.***>
Lähetetty: sunnuntai 3. marraskuuta 2024 8.41
Vastaanottaja: jisotalo/shelly-porssisahko ***@***.***>
Kopio: KSkalliswatti ***@***.***>; Mention ***@***.***>
Aihe: Re: [jisotalo/shelly-porssisahko] Useampikanavainen rele - oma ohjaus eri kanaville (Pro4PM) (Issue #16)


@KSkalliswatti<https://github.com/KSkalliswatti>

Hienoa!

Sinänsä ihan totta, että nyt joku voi laittaa väärälle ohjaukselle. Mutta omasta mielestäni se on käyttäjän vika. Parempi vaan että oletusasetukset ovat sinänsä toimivat ja lähtö 0 löytyy varmasti kaikista laitteista.

**Comment by tkkoivula** [comment]
Nonii, laitoin tuon beta-kakkosen sitten etänä ajoon PlusPlugS-palikkaan. So far so good. :)
Täytyy nyt odottaa kuitenkin että pääsen kotiin ennenkuin testaan oikeasti Pro4PM:n kanssa.

**Comment by vettenj** [comment]
Täällä on nyt beta2 ajossa Pro3:ssa.

Oliko noille pakko-ohjauksille joku syy, miksi taulukossa on ensin OFF ja viimeisenä ON? Käänteinen puolalainen logiikka tms? Ehkä osin makuasiakin, mutta näkisin loogisempana järjestyksen ON/-/OFF tai ON/OFF/- TAI -/ON/OFF.

Ratkaisin tuon KSkalliswatin kaipaaman mitä minkäkin kanavan takana on, nimeämällä IP-kohtaisesta ohjauspaneelista Device name näin: "Pro3 out1=LVV out2=lattialämmitykset out3=kattolämmitykset". Toinen vaihtoehto olisi avata Tila-ikkuna oletuksena useamman kanavan ollessa käytössä valmiiksi näyttämään alasvetolistaa (jos onnistuu), jolloin valittu näkyisi sinisellä pohjalla ja samalla näkyisivät muutkin (kuva liitteenä). Tämä alkaa tosin olla jo hieman hifistelyä, eikä välttämättä avautuisi ihan kaikille käyttäjille, miksi se noin toimisi.

Kehitysehdotuksena, kun asetukset tallennetaan, niin Tallennettu! -ikkuna voisi sulkeutua sekunnin-kahden viiveen jälkeen ja siirtyä suoraan Tila-ikkunaan, kun sinne luultavimmin seuraavaksi kuitenkin mennään tutkimaan miten muutettu asetus vaikutti.

Pro3:ssa muistin käyttö näyttää nyt tältä, pari muutakin skriptiä sinne on talletettu, mutta ne eivät ole ajossa:
  "script:1": {
    "id": 1,
    "running": true,
    "mem_used": 11928,
    "mem_peak": 18312,
    "mem_free": 13258
  },

![image](https://github.com/user-attachments/assets/8dc3e0c1-91ad-4048-ab23-5ba6dbcd54af)

**Comment by KSkalliswatti** [comment]
Hyvin on 3-versio pyörinyt
Ajan 0-kanavaa #1-sivulla "jakson halvimmilla" tunneilla ja 0-kanavaa #2-sivulla "hintarajalla"
1-kanavaisessa "Töpselissä" (Shelly Plus Plug S)
Lokin mukaan #1 tekee ensin hommansa ja #2 ajaa päälle omansa ja muuttaa tilan, jos eri mieltä.
eli #2 muuttaa tilan oman ohjauksen mukaiseksi. Lokissa #2 tulee sekunnin perässä.
Homma toimii.
Tällaista ei käytännössä tarvita, mutta kokeilin, kun arvelin toimivan.
Nettilinja mökillä "pätkii" ja siitä homma on hyvin selvinnyt.

Asetukset- historia- ja tilasivu ihan hyvät
Tilasivulla vois väkäsen vieressä olla joku merkki, jos sen aiheuttaa joku muu kuin pääohjaustyyppi
(Väkäset tulee hinnan mukaan, mutta esim. seassa on yksi pakko-ohjaus)

Näitä hienouksia tehdään sitten, kun homma toimii ja tilaa jää "hienouksille"

**Comment by vettenj** [comment]
Minulla on ollut ajossa ohjaus kanaville 0, 1 ja 2. Siinä kytkeytymisjärjestys vaikuttaa satunnaiselta, esim. eilen klo 22 kun kaikki muuttivat tilansa, niin järjestys oli 2, 0 ja 1.

**Comment by jisotalo** [comment]
Lähtökohtaisesti pitäisi kyllä mennä ohjausjärjestyksessä 1,2,3. Skriptin konsolista näkee missä järjestyksessä ajaa.

> Asetukset- historia- ja tilasivu ihan hyvät Tilasivulla vois väkäsen vieressä olla joku merkki, jos sen aiheuttaa joku muu kuin pääohjaustyyppi (Väkäset tulee hinnan mukaan, mutta esim. seassa on yksi pakko-ohjaus)

Tämä voisi olla ihan hyvä lisä.

> Oliko noille pakko-ohjauksille joku syy, miksi taulukossa on ensin OFF ja viimeisenä ON? Käänteinen puolalainen logiikka tms? Ehkä osin makuasiakin, mutta näkisin loogisempana järjestyksen ON/-/OFF tai ON/OFF/- TAI -/ON/OFF.

Ei ole mitään muuta syytä, kuin se, että itselle tuntui tehdessä loogiselta.

> Kehitysehdotuksena, kun asetukset tallennetaan, niin Tallennettu! -ikkuna voisi sulkeutua sekunnin-kahden viiveen jälkeen ja siirtyä suoraan Tila-ikkunaan, kun sinne luultavimmin seuraavaksi kuitenkin mennään tutkimaan miten muutettu asetus vaikutti.

Tälle ei valitettavasti voi mitään, kun käyttää selaimen omaa `alert()` -ilmoitusta.

> Koska on kulutusmittauksella varustettuja Shellyjä ja siirtohinta ja alvi ja sähkövero tiedetään voidaan laskea hinta ja näyttä se Ja tässä monikanavaisessa vois olla jossain rivi, joissa näkyis koko ajan mitä mikäkin kanava ajaa
Tuon laskennan voi tehdä halutessaan itse jos siltä tuntuu.

Sinänsä voisi olla hyvä lisä status-sivulle tuo, että mitä lähtöjä ohjaus ohjaa. Toisaalta, ehkä hieman turhaa tietoa, kun sen näkee asetusivulta ja lähtökohtaisesti sen voi hoitaa tuon nimen avulla. Esim nimeää vaikka ohjauksen 1 nimellä `Varaaja (lähtö 0)`. Ja ei sillä tiedolla varmaan tee enää mitään kun on kerran saanut toimiin. Mutta mietitään!


Lähtökohtaisesti pyrin välttämään enää kasvattamasta skriptiä, vielä tuntuu muistin käyttö olevan hallinnassa!

**Comment by vettenj** [comment]
> Lähtökohtaisesti pitäisi kyllä mennä ohjausjärjestyksessä 1,2,3. Skriptin konsolista näkee missä järjestyksessä ajaa.
 
Tarkistin tuon tänään, kaikki kanavat skriptillä ON-tilaan klo 22: konsolista katsottuna menivät ihan järjestyksessä, samaan aikaan otin videota Pro3:sta ja siinä tosiaan kanavien kytkeytymisjärjestys oli 2, 0 ja 1. Testasin vielä Shellyn cloud apilla kännykällä, että kanavien järjestys täsmäsi sen kanssa, mitä Device information näytti. Onpa mysteeri! 
![image](https://github.com/user-attachments/assets/bb81330e-c2f6-4fbb-8912-3febe5ca7e98)

**Comment by vettenj** [comment]
Testasin myös skriptin toimivuutta Shelly Plus Plug gen2:lla ja gen3:lla. Jo aiemmin huomasin gen3:ssa bugin, siinä ei skriptin print-komento toimi. Myös suoritus kaatuu out of memoryyn. Gen2:lla toimii ilman ongelmitta.

**Comment by vettenj** [comment]
Tällainen havainto, ei ole kovinkaan vakavaa: jos tallennuksen jälkeen menee liian hätäisesti Tila-välilehdelle, niin saattaa tulla tällainen virheilmoitus, josta ei toivu itsestään, ennen kuin painaa refresh. Eli skripti pyörii kyllä taustalla eikä kaadu, ainoastaan käyttäjä saattaa olla hetken epätietoisuudessa mitä tapahtui. 
![image](https://github.com/user-attachments/assets/cb10a80f-e33a-4acc-91cc-fdd1ace396b1)

**Comment by KSkalliswatti** [comment]
Vastaus: On siisti ja asia käy hyvin selville. (Ja tehty varmaan mahdollisiman vähillä biteillä)

**Comment by KSkalliswatti** [comment]
Tämä ehdotuseni ja ratkaisu
"Ja tässä monikanavaisessa vois olla jossain rivi, joissa näkyis koko ajan mitä mikäkin kanava ajaa"

Ratkaisin tuon KSkalliswatin kaipaaman mitä minkäkin kanavan takana on, nimeämällä IP-kohtaisesta ohjauspaneelista

Tätä en tarkoittanut vaan esim rivi näyttäis tälle

ht_12h__5__*__* / hr_0.75__*_20 / *

Ykköskanava siis  "halvimmat tunnit" 12tunnisa 5kpl ainapäällä ja maksimihinta perusasennossa
kakkoskanaali hintaraja nollaseitenviis ja ainapäällä perusasennossa ja maksimihinta 20senttii
kolmone eikäytös

Srispti siis lukee ja näyttää mitä mun syöttämillä parametreillä se tekee
Voi olla vähän vaikea datoista tätä "kasata" ja vie muistia...…………..
ja mitä muuta siihen pitäis mahtua?

Kun nämä kotikoneet alko kovasti lisääntyä ja vanha isäni myös tietokoneesta kiinnostui ja sellaisen hankki.
Jouduin isälleni muutaman kerran sanomaan, että "Tietokone tekee niinku sää käsket ei niinku sää ajattelet"
Eli skripti näyttää koko ajan mitä sille on syötetty

**Comment by jisotalo** [comment]
Nyt on beta 3 ulkona! Samalla tein myös version, jossa on yksi ohjaus eikä historiaa. Eli jos haluaa vaan ohjata jotain mahdollisimman pienellä muistinkäytöllä.

Jos ei tule ongelmia vastaan, alkaa olla julkaisuvalmis. Ainoastaan nuo käyttäjän omat lisäskriptit vielä puuttuvat.

## [3.0.0-beta3] - 06.11.2024
- Näytetään ohjausrivillä ***, jos kyseessä on pakko-ohjaus
- Jos sivun lataaminen epäonnistuu, mahdollistetaan uudelleenyritys
- Lisätti oma versio, jossa vain yksi ohjaus ja ei historiaa (pienempi muistin käyttö)
- Pieniä fiksejä

@KSkalliswatti muutin tuon pakko-ohjauksen näyttämisen vielä tähän muotoon:
![image](https://github.com/user-attachments/assets/dd138ef6-1cdf-4d4f-93d9-257d0f12c468)

**Comment by jisotalo** [comment]
> Testasin myös skriptin toimivuutta Shelly Plus Plug gen2:lla ja gen3:lla. Jo aiemmin huomasin gen3:ssa bugin, siinä ei skriptin print-komento toimi. Myös suoritus kaatuu out of memoryyn. Gen2:lla toimii ilman ongelmia.

Sain muuten sähköpostitse raporttia että toisellakin on gen 3 kanssa ongelmia. Onkohan siinä joku bugi tosiaan, kun kaikilla muilla laitteilla toimii.

**Comment by vettenj** [comment]
Joo tuosta bugista oli asennuksen tehneen sähkärin (on myös maahantuojan roolissa) kanssa puhetta, etten ollut ainoa joka sen huomasi. Käsittääkseni hän laittoi bugista viestiä Shellylle Romaniaan.

Nyt on beta3 pyörimässä Pro3:ssa. Pakko-ohjauksen päättymisestä näyttää tulevan pelkkä ** ilman väkästä, ellei ole muita ohjauksia, se oli kai tarkoituskin? 
![image](https://github.com/user-attachments/assets/e9c1b33c-c0f7-46aa-a93b-ca983b57b358)

**Comment by jisotalo** [comment]
@vettenj 

Tuo pelkkä ** meinaa että sillä tunnilla on pakko-ohjaus pois. Eli asetuksista on laitettu että aina klo 23A ohjaus on pois (OFF) vaikka olisikin halpaa

**Comment by KSkalliswatti** [comment]
Näyttäs siltä, ettei tuntia 23 saa ollenkaan mukaan omaan ajanjaksoon.  Ajanjakson myöhempi aika on aina ensimmäinen pois jäänyt aika.

**Comment by vettenj** [comment]
Näillä asetuksilla näyttäisi sekin tulevan mukaan: 
![image](https://github.com/user-attachments/assets/91528194-d9a0-4f47-9bdf-623b1d935896)
![image](https://github.com/user-attachments/assets/198d3c5c-7ed3-4048-a4f6-84d7b586a031)
Yritin ensin laittaa tunnit 22-23, ei toiminut kaksi tuntia niillä, 22-24 toimii.

**Comment by vettenj** [comment]
![image](https://github.com/user-attachments/assets/6e71535a-6dd3-4bff-bf2c-01a2d997bf86)

**Comment by vettenj** [comment]
Nyt kun tunti vaihtui, niin kaikki tottelevat taas halvimpia hintoja. 
![image](https://github.com/user-attachments/assets/9ab82d46-b9a7-4c8f-b60e-fe04f4666248)

**Comment by vettenj** [comment]
Tänään oli kaikki skriptit (myös Plugeissa pyörivät) varmuustuntiohjauksilla. Käynnistin kaikki skriptit uusiksi ja nyt ohjaavat halvimpien hintojen mukaan. Eikö skripti palaudu omin avuin varmuustuntiohjauksesta takaisin hintaohjaukseen?

**Comment by jisotalo** [comment]
Eleringillä on ongelmia eikä hintadataa ole saatavilla. Ei johdu siis tästä 3. versiosta. Eiköhän se päivän mittaan korjaannu.

**Comment by jisotalo** [comment]
> Tällaisen havainnoin tein nyt: paitsi että kaikista ohjauksista puuttuu huomisen hinnat, niin lisäksi ohjaus #1 on varmuustuntiohjauksella. Ohjaukset 2 ja 3 menevät edelleen halvimpien tuntien mukaan. Ohjaustapana kaikissa on Jakson halvimmat tunnit. Miksi vain yksi kolmesta kanavasta on varmuustuntiohjauksella, jos kuluvan vuorokauden hinnat ovat saatavilla, mutta huomisen ei ole (tänään on ollut ongelmia huomisen hintojen haussa)? Ymmärtäisin jos kaikki olisivat varmuustuntiohjauksella, mutta nyt on vain yksi kolmesta. En ole vielä kokeillut stopata ja käynnistää skriptiä uusiksi. 

Julkaisin juuri beta4, joka pitäisi korjata tätä. 

Tässä luultavasti kävi niin, että hinnat oli aiemmin saatu ja sen jälkeen Elering hajosi. Sitten kenties päivitit ohjaus #1 asetuksia, jolloin hintojen haku epäonnistui -> ohjaus 1 meni varmuustunneille. Kuitenkaan 2. ja 3. ohjausten logiikkaa ei ajettu uudelleen ja ne eivät tehneet mitään.

[3.0.0-beta4] - 08.11.2024
- Parannettu toimintaa vikatilanteissa (jos hinnat puuttuvat / virheelliset)
- Ajetaan kaikki ohjaukset aina hintojen saannin / virheellisen hintadatan jälkeen
- Kun asetukset tallennetaan, ajetaan kaikki ohjaukset läpi
  - Saadaan kaikki ohjaukset varmasti ajan tasalle

**Comment by KSkalliswatti** [comment]
Minullehan kävi seuraavasti.......
Katkaisin nettilinjan testitarkoitukseksi ja sit kun laitoin linjan päälle en tiennyt, että Viro oli silläaikaa seonnut.....
Pistin nettilinjan päälle ja sit tosiaan vähänaikaa ihmettelin, että mitä mitäs tämä nyt tekee.
No sit selvis, että tosiaan hintojenhakupaikka ei toimi.
Jatketaan testejä 30 B4 pyörii Plus2PM-laitteessa

**Comment by vettenj** [comment]
Käyttöliittymä ei osannut eilen Eleringin toipumisenkaan jälkeen näyttää/hakea uusia hintoja vaikka painoi F5, piti painaa ctrl-F5 niin haki hinnat näkyville.

Päivitin eilen beta4:n ja ohjaus #2 oli jäänyt aamulla klo 7 kytkeytymättä pois, vaikka skriptin historian ja Shellyn konsolin mukaan niin olisi pitänyt tapahtua. Ei ole selvinnyt, mistä johtuu, mutta Chromessa on nyt kymmeniä välilehtiä auki ja siksi tuntuu läppäri nyt kovin hitaalta. Voisiko läppäri kuormittaa Wifiä niin, että skriptin komennot eivät mene perille? Shellyn konsoliin ne ovat kuitenkin menneet perille. Pro3:n firmistä en ole tarkoituksella päivittänyt, on se aiemmilla beta-versioilla kuitenkin toiminut.
![image](https://github.com/user-attachments/assets/249e5edb-639d-4961-8d88-431cbeac3c77)
![image](https://github.com/user-attachments/assets/c27e59fb-3dd2-4984-8e73-20717bc20085)
![image](https://github.com/user-attachments/assets/9744571f-de83-4c87-8ed1-93980b5042e8)

**Comment by vettenj** [comment]
No niin nyt selvisi miksi ohjaus #2 oli jäänyt päälle: asetuksissa sen ohjattava lähtö oli 0 (aiemmin 1), kun taas beta-päivityksessä ohjaukset #1 ja #3 olivat säilyttäneet aiemmat tilansa (jotka olivat 0 ja 2). Skripti teki siis juuri sen mitä käyttäjä oli asettanut.

**Comment by vettenj** [comment]
Testasin nettiyhteyden katkaisua reitittimestä. Näyttää siltä, että vaikka Tila-välilehdellä painaa silloin F5 tai ctrl-F5, niin ei oikeasti hae hintoja, vaikka tilana näkyykin "haetaan...". Vasta kun Asetukset-välilehdellä tallentaa, niin hakee hintoja ja menee yhteyden puuttuessa varmuustuntiohjaukselle.

**Comment by jisotalo** [comment]
F5 painamisesta ei ole mitään hyötyä.

Hinnat haetaan kun
- vuorokausi vaihtuu
- kello 15
- kun asetukset tallennetaan

**Comment by vettenj** [comment]
Totta, skripti toimii tietysti vain moottorina hintojen haulle oman logiikkansa mukaan ja muodostaa käyttöliittymäsivun. Käyttöliittymää voi yrittää virkistää F5:lla, mutta ei se saa skriptiä muuttamaan logiikkaansa. Enpä heti tullut ajatelleeksi tätä. Kiitos selvennyksestä.

**Comment by tkkoivula** [comment]
Beta-4 nyt ollut ajossa Pro4PM:ssä 3vrk. Kahta lähtöä ohjataan kahdella eri ohjeella, hyvin näyttää pelaavan.

**Comment by KSkalliswatti** [comment]
Shelly Plus 2 PM testini oikeastaan tehty. En osaa sitä enempää "kiusata"
Kaikki toimii hyvin. 
Odotan talvea ja sähköyhtiöiden hinnanmanipuloinnin huippua. (Vuorotellen voimala remonttiim, niin saadaan hinta 10-kertaistettua.)

**Comment by jisotalo** [comment]
Hienoa kuulla, kiitos teille! 

Koitan julkaita tänään tuon 3.0.0 virallisesti. Beta4 jälkeen ei ole enää tullut muutoksia.

Jätän nuo omien lisäskriptien tuen myöhemmäksi. Jos niitä haluaa käyttää, v2 löytyy yhä jatkossakin.

**Comment by jisotalo** [comment]
Dodiin v.3.0.0 julkaistu. Pidän tämän issuen vielä hetken auki, jos tulee jotain. 

Päivitelkäähän pois betaversioista kun joudatte!

**Comment by vettenj** [comment]
Päivitetty täällä v.3.0.0 Pro3:een, kahteen Plus Plug gen2:een ja yhteen Plus Plug gen3:een. Viimeisessä kaatuu virheeseen, eikä ole ensimmäinen kerta kun tuo gen3 aiheuttaa ongelma:
shelly_notification:163 Status change of script:4: {"id":4,"errors":["out_of_memory"],"running":false}
Tästä syystä se ei ole "tuotantokäytössä", parempaa firmwarea odotellessa.

Hienoa että jaksoit kehittää tällaisenkin version, jossa on ainakin minulle kolme tärkeää ominaisuutta: 1) ei kaadu Pro-Shellyillä muistin loppumiseen ja 2) samalla skriptillä voi ohjata useampaa kanavaa jokaista omilla monipuolisilla asetuksillaan ja 3) näppärän käyttöliittymän kautta on helppoa ja kätevää muuttaa asetuksia ilman, että skriptiin tarvitsee koskea.

**Comment by KSkalliswatti** [comment]
Asensin viralliset 30-versiot
Tähän vanhaan 1-kanavaiseen Shelly Plus Plug S laitteseen (tässä pyöri ennen 2-kanava beta) asensin uuden 30 1-kanava skriptin
Vanha #2 jäi kummittelemaan. Nimi näkyy valikossa ja valitsemalla sen selain jää pyörimään "tyhjää"
Tietoja ei saa pois, koska lisäkanavia ei ole

**Comment by KSkalliswatti** [comment]
muut nimet pois ja save. Sitten skripti seis ja uudestaan käyntiin. Jep näin on. Onnisu
(On kiva kun voi "kilauttaa kaverille")
