### ISSUE TITLE
Kehitysehdotus

### ISSUE THREAD

**Issue by lahna11** [jisotalo/shelly-porssisahko#24]
Rajapinta, josta haetaan poikkeuksia. Esim. Paneelit tuottavat sähköä mutta sitä ei kannata myydä --> käyttöön.

**Comment by jisotalo** [comment]
Moro!

Minkälaista rajapintaa tarkoitat noin niinkun teknisesti? Voitko avata vähän mitä on mielessä

**Comment by jisotalo** [comment]
@lahna11?

**Comment by lahna11** [comment]
Hei!

 

En tunne teknisesti mikä kaikki on teknisesti järkevää / helppoa näiden skriptien kanssa. Ajatus kuitenkin oli, että jotenkin saisi skriptin tietoiseksi siitä jos omaa tuotantoa on paljon eli tällöin voisi ohjata laitteita päälle.

Hommaan liittyy se, paljonko pörssistä sähköstä saa: jos päivällä sähkö on tarpeeksi kallista, se kannattaa joka tapauksessa myydä ja ostaa takaisin esim. yöllä halvoilla tunneilla.

 

Voisiko skripti ottaa vastaan tuotantomäärän esim. json-muodossa vaikka restillä tai mqtt:llä? Vai olisiko halpompi jos skripti itse hakisi tuotannon jostakin urlista esim. json-muodossa?

 

 

 

Sent: Friday, March 01, 2024 at 11:54 AM

**Comment by jisotalo** [comment]
Tuo on ihan tehtävissä jo nyt custom-skriptillä.

[Tässä esimerkissä](https://github.com/jisotalo/shelly-porssisahko?tab=readme-ov-file#esimerkki-ohjaustuntien-asetus-l%C3%A4mp%C3%B6tilan-perusteella-erillinen-shelly-ht) otetaan vastaan json-dataa, jonka perusteella muutetaan tuntimäärää:
https://github.com/jisotalo/shelly-porssisahko/blob/master/dist/shelly-porssisahko-ht-sensor-temp.js

[Sääesimerkki](https://github.com/jisotalo/shelly-porssisahko?tab=readme-ov-file#esimerkki-ulkol%C3%A4mp%C3%B6tilan-hakeminen-s%C3%A4%C3%A4palvelusta-ja-sen-hy%C3%B6dynt%C3%A4minen) täytyisi vielä tehdä, mutta siinä on ajatus hakea rest-pyynnöllä päivän sää ja muokata tuntien määrää. 

Eli molemmat on aika helposti tehtävissä, jos tietää miten haluaa toiminnan menevän.

**Comment by lahna11** [comment]
Hei!

 

Kiitokset vastauksesta! Tutkin näitä hiukan ja näytti että myös shelly-porssisahko-addon-temp.js olisi sopivat tähän:

- jos sähkö on halpaa ja sitä tulee paljon --> override

- jos sähkö on kallista (sitä kannattaa myydä) tai sitä ei tule --> pörssisähköohjaus

 

En vielä ehtinyt niin pitkälle että olisin tutkinut miten tuolle addonille saisi tuon tiedon parhaiten annettua (eli pitää ihmetellä miten haen jonkun arvon verkosta johonkin muuttujaan). Kun tuo olisi muuttujassa, saisi tuolla esimerkillä ilmeisesti joka tunti overriden sen perusteella mitä joku muu logiikka toisaalla päättää.

 

Kiitokset vielä, hieno ja tosi hyödyllinen skritpi!

 

 

 
 

Sent: Thursday, March 07, 2024 at 8:58 PM
