### ISSUE TITLE
Ongelma, jos Nord Poolin hinnat virheelliset kello 15

### ISSUE THREAD

**Issue by jisotalo** [jisotalo/shelly-porssisahko#26]
Laitan nyt bugin, vaikka ei sinänsä ole.

Eilen Nord Poolilla oli ongelma hintojen toimittamisessa. Elergin kuitenkin palautti seuraavan vuorokauden hinnat siten, että lähes joka tunnilla oli 0.00 c/kW (eli ei antanut virhettä, vaan hinnat oli nollassa).

https://www.nordpoolgroup.com/en/trading/Operational-Message-List/2024/04/day-ahead-delay-in-final-market-coupling-results-publication-20240416110900/

Koska skripti hakee seuraavan päivän hinnat klo 15, jäivät nämä virheelliset hinnat voimaan. Skripti ei voinut tietää mistään, että hinnat eivät ole lopulliset.

Liikenteen minimoimiseksi seuraavan päivän hinnat kopioidaan klo 00.00 nykyiselle päivälle, joten virheellisiä hintoja ei korjattu silloinkaan.

Ainoa tapa korjata tämä ominaisuus on poistaa tuo liikenteen minimointi siten, että päivän hinnat haetaan aina klo 00.00, vaikka ne ovat jo tiedossa. Näin mahdolliset Nord Poolin virheet saadaan korjattua.

Jos joku näkee tämän tänään 17.04.2024, hinnat saa korjattua painamalla "tallenna"-nappia skriptin asetuksissa :)

**Comment by iiseppi** [comment]
Oliskos tuossa mitään järkeä laitta tuo hakuaika käyttäjän valittavaksi? Näin voisi laittaa eri aikoihin noita hakuja, esim. 18:17 jolloin ei varmaan automaattisesti ole paljon hakuja...
Tai sitten jokin tunti esim. 16:00 minkä minuutit scripti arpoisi satunnaisesti... Vai tuleeko muisti sitten jo vastaan?

**Comment by jisotalo** [comment]
Kyllä tuon teknisesti voisi asetukseksi laittaa. En vaan näe siitä mitään hyötyä.

Kunhan teen tämän muutoksen, alkavan päivän hinnat haetaan aina kello 00.00. Elikkä eipä siinä mielestäni muuta tarvita.

**Comment by iiseppi** [comment]
Näinhän se taitaa olla. Itse ehkä ajattelin siltä kantilta, että voi seuraavan päivän ajastukset tarkistaa vielä jos hinnat on valmiina iltapäivän/illan aikana. 
Mutta tuo sinun ajatus kyllä ratkaisee tuon hakuasian.

**Comment by jisotalo** [comment]
Muutos julkaistu versiossa 2.13.0

**Comment by tkkoivula** [comment]
Ja vielä sellainen huomio että skripti säätää aina 2min välein lähdön varmuustuntiohjauksen mukaan vaikka
![image](https://github.com/user-attachments/assets/a9124c2c-395b-457b-ae1f-94e9bfdd641d)

**Comment by jisotalo** [comment]
Joo siellä on eleringillä ollut ongelmia. Täytyykin tsekata tuo lähdön kirjoitus, että voiko tuolle tehdä jotain.

**Comment by tkkoivula** [comment]
Mulla täällä ulkovaraston lämmitys hoidettu niin että skripti pätkii lämmitintä jossa oma termari. Toinen komento tulee tunnin välein Homeassistentilta: jos lämpötila putoaa alle 4 asteen, laitetaan lämmitys päälle hinnasta riippumatta. No nyt skripti laittoi lämmityksen pois päältä 2min välein. Sinänsä ei hätää, ei tuolla mitään jäädy vaikka menisikin pakkaselle.

**Comment by jisotalo** [comment]
Joo ei tuossa kyllä järkeä ole! Tein issuen #37
