### ISSUE TITLE
dist/shelly-porssisahko-ht-sensor-temp.js

### ISSUE THREAD

**Issue by AnttiTeodor** [jisotalo/shelly-porssisahko#28]
20:11:35: shelly-porssisahko v.2.13.0 20:11:35
20:11:35: URL: http://192.168.0.163/script/3 20:11:35
Uncaught Error: Cannot read property 'cnt' of undefined 20:11:35
at originalConfig.hours = config.m2.cnt; 20:11:35
^ 20:11:35
in function "USER_CONFIG" called from ...&&(_.c=USER_CONFIG(_.c,_,!0));{t=function(e){_.s.configOK=e?... 20:11:35
^ 20:11:35
in function called from system

Tuommonen tulee. H&T lämpötila näkyy Home Assistantissa päivittyneenä minuutteja sitten mutta skripti ei ota käynnistyäkseen ylläolevalla virheellä.

**Comment by jisotalo** [comment]
Moro! Minäpä tsekkaan tuon kun vaan ehdin. Kiitos!

**Comment by jisotalo** [comment]
Moi, voitko testata uudella versiolla (3.0.0)?

**Comment by AnttiTeodor** [comment]
Nyt ei ihan aukea tuo mikä on "perusskripti", voitko tarkentaa.
Kiitos kuitenkin hyvästä työstä, sähkölämmittäjät kiittää.

Tony

**Comment by jisotalo** [comment]
Joo vähän epäselvästi sanottu. Eli siis tämä:
<img width="479" alt="image" src="https://github.com/user-attachments/assets/eb70f964-416b-41e0-a5c9-30997d760d1c">

**Comment by jisotalo** [comment]
Hienoa! Tämä pitäisi nyt olla korjattu jatkossa
