### ISSUE TITLE
Apua 

### ISSUE THREAD

**Issue by Okkim87** [jisotalo/shelly-porssisahko#30]
Sain asennettua scriptin mutta ei kytke halvimpien tuntien mukaan. Vain shellyn katkaisin napista kytkee päälle/pois. Scripti antaa herjaa: 

shelly-porssisahko: setting output 1 failed: -105 - Argument 'id', value 1 not found! 

Releenä 1pm

**Comment by jisotalo** [comment]
Moro @Okkim87 

Koitappa pistää lähdön numeroksi `0` ykkösen sijaan. Nyt se yrittää ohjata lähtöä, jota ei 1pm-mallissa ole.

**Comment by Okkim87** [comment]
No siitähän se kiinni oli, kiitos
