### ISSUE TITLE
Ohjauksen muutosta.

### ISSUE THREAD

**Issue by petri1973** [jisotalo/shelly-porssisahko#4]
Moi.

Onko mahdollista muuttaa / tehdä toista versiota, jossa olisi ns. pakkotunnit kun shelly aktiivisena, eli pakotettuna?

Ideana, siis että vaikka hinta olisi mikä tahansa, niin esim klo 04-0700 ja 16-1900 rele päällä?

(Ohjaus lämminvesivaraajalla, ja pyrkimys että vesi on tiettyinä aikoina mahdollisimman lämmin kun sitä eniten tarvitaan). :)

**Comment by jisotalo** [comment]
Moi!

Tuo on hyvä idea. Uskon että muisti riittää vielä siihen, täytyy kokeilla.

Sen voisi laittaa asetussivulle samalla tavalla kuin nyt on nuo varmuustunnit, eli checkboxeina.

**Comment by petri1973** [comment]
Huomasin myös että vaikka scheduled Shellyllä päällä aktivoida rele tiettyinä kellonaikoina, scripti tuntuu olevan kuitenkin hallinnassa prioriteettina. Joten vaikka scheduled power on, niin rele on esimerkiksi itsellä juuri nyt pois päältä kun hinta yli asetetun arvon.

**Comment by jisotalo** [comment]
Moro! Julkaisin nyt v.2.2.0 jossa on tuo ominaisuus. Haluatko testata?

Ainakin omissa testeissä toimii hyvin ja samalla myös paljon pieniä parannuksia.

**Comment by petri1973** [comment]
Testiin laitettu, sekä työkaverikin testaa tätä paraikaa.
Aivan mahtavaa kun olet vääntänyt koodia, tässä on vielä hieno juttu tämä web sivu josta pääsee simppelisti klikkaamaan mitä haluaa. 
Testaillaan, ja vielä kerran kiitokset! :)

**Comment by jisotalo** [comment]
Kiitos palautteesta, kiva jos omasta räpeltelystä on hyötyä muillekin :) Laita vaan issueta kehiin jos on ideoita tai ongelmia.

Vuorokauden hinnat haetaan aina kun vuorokausi vaihtuu (tai kun skripti käynnistyy). Eli yöllä kun tsekataan klo 00 hinta, haetaan koko päivän hinnat samalla. Eli tuosta ei ole mitään hyötyä jos ne haettaisiin joka tunti kun ne on jo tiedossa.

Ja tietysti kun tunti vaihtuu niin katsotaan sen tunnin hinta ja toimitaan sen mukaisesti.
