### ISSUE TITLE
0€ hinnat 

### ISSUE THREAD

**Issue by iiseppi** [jisotalo/shelly-porssisahko#40]
Millä laskukaavalla mahtaa osa 0€ hinnoista mennä miinusmerkkisiksi?
Esim. tuleva yö klo 1, 4 ja 5  on -0.00€ ja klo. 2 on 0.00€.
Esim. teksti-tv näyttää hinnat pelkkinä 0€ hintoina. :) 

![hinnat](https://github.com/user-attachments/assets/0b014d6d-358c-4a67-950a-b429276961b4)

**Comment by jisotalo** [comment]
Moro, tuolta se tulee Eleringin lähdedatan perusteella:

![image](https://github.com/user-attachments/assets/4aa8177f-8483-45c3-b125-a0a1c5a40d70)

**Comment by iiseppi** [comment]
Aivan, tuoltahan se sitten tulee, eli todellinen hinta on halvempi kuin 0€. 
Kiitos!

**Comment by jisotalo** [comment]
Eipä mitään, vähän hämäävä kyllä!
