### ISSUE TITLE
Lämmitystuntien lukumäärä paikkakunnan ulkolämpötilan mukaan

### ISSUE THREAD

**Issue by Mkrhx** [jisotalo/shelly-porssisahko#6]
Onko mahdollista saada sellaista toiminallisuutta, että 

1) Käyttäjä valitsee oman paikkakuntansa
2) Haetaan paikkakunnan lämpötilaennuste 
3) Itse toiminnallisuus. Käyttäjä voisi asetella, että ulkolämpötilaennusteen ollessa C astetta niin lämmitystunteja on X kappaletta.

Esim. Lämpötilaennuste -30c => lämmitystunteja 10kpl. Lämpötilaennuste -20c => lämmitystunteja 6kpl. Lämpötilaennuste -5c => lämmitystunteja 4kpl.

Näin saisi optimoitua, että käytetään aina edullisimpia tunteja lämmitykseen.

Kiitos tästä jo nykyisellään. Tämä on kyllä mahtava.

**Comment by jisotalo** [comment]
Moi ja kiitos kehuista!

Sinänsä ihan hyvän kuuloinen ominaisuus. Shellyn muistissa vaan ei ole tuolle lisäykelle enää tilaa, täytyisi tehdä riisuttu versio (poistaa käsiohjaus ja hintarajaohjaus) jolloin varmaan mahtuisi.

Täytyy pitää mielessä jos löytyy joskus inspiraatio!

**Comment by jisotalo** [comment]
Moro

Tämän tekeminen olisi nyt 2.8.0 versiolla mahdollista. Katsotaan milloin kerkiäisin tekemään esimerkin.

**Comment by jisotalo** [comment]
Nyt uudessa versiossa 2.10.2 on esimerkki miten tämä tehdään Shelly H&T -anturin avulla. En vielä ole kerennyt tekemään sääennustetta varten, mutta jos tuo "golfpallo" löytyy sitä voi hyödyntää.

**Comment by jisotalo** [comment]
Moro @Mkrhx 

En tiedä onko sulle enää ajankohtaista, mutta nyt tuli lauantai-illan ratoksi näprättyä tämä.

Tsekkaa: <https://github.com/jisotalo/shelly-porssisahko?tab=readme-ov-file#esimerkki-ulkol%C3%A4mp%C3%B6tilan-hakeminen-open-meteo-s%C3%A4%C3%A4palvelusta-ja-sen-hy%C3%B6dynt%C3%A4minen>

Eli asentaa library-napin takaa **Esimerkki: Ulkolämpötilan hakeminen Open-Meteo-sääpalvelusta ja sen hyödyntäminen**. Sitten muokkaa oikeat koordinaatit ja toimintalogiikan.
