### ISSUE TITLE
Fetching EE prices

### ISSUE THREAD

**Issue by Elev5** [jisotalo/shelly-porssisahko#8]
First, thank you so much for this. It's amazing.

I've [forked](https://github.com/Elev5/shelly-porssisahko-EE/tree/master) this and tried to query prices for EE by changing the Elering API address to [https://dashboard.elering.ee/api/nps/price/csv?fields=ee&start=](https://dashboard.elering.ee/api/nps/price/csv?fields=ee&start=) but it still seems to fetch Finnish prices. Any idea what could be the issue?

**Comment by jisotalo** [comment]
Thanks! 

Actually I have a plan to integrate country selection (and create english build) at some point. However the memory limit is already very close.

It seems to work OK if you change fi -> ee:

FI:
https://dashboard.elering.ee/api/nps/price/csv?fields=fi&start=2023-10-30T00:00:00%2b02:00&end=2023-10-30T23:59:59%2b02:00

EE:
https://dashboard.elering.ee/api/nps/price/csv?fields=ee&start=2023-10-30T00:00:00%2b02:00&end=2023-10-30T23:59:59%2b02:00

Did you run the `npm run build` command after changing the code? So you get a built version to `./dist` directory?

**Comment by Elev5** [comment]
Thank you!  `npm run build` command is very likely what I'm missing (I'm very new to programming and just started). I will try it out as soon as possible. 

Country selection and english build would be very much appreciated, but this version is already amazing and so helpful.
